# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# 4k Radarr
radarr:
  radarr4k:
    base_url: !secret radarr4k_url
    api_key: !secret radarr4k_api
    media_naming:
      folder: default
      movie:
        rename: true
        standard: plex-tmdb
    media_management:
      propers_and_repacks: do_not_prefer
    delete_old_custom_formats: true

    # Quality Definition
    quality_definition:
      type: sqp-uhd

    # Quality Profiles
    # https://github.com/TRaSH-Guides/Guides/tree/master/docs/json/radarr/quality-profiles
    # Manual overriding to remove 1080p qualities from the synced profiles
    quality_profiles:
      - trash_id: 2cf36c1f0106ffac993be003ade51865  # [SQP] SQP-3
        name: SQP-3 (Remux)
        qualities:
          - name: WEB|Remux|2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
              - Remux-2160p
        reset_unmatched_scores:
          enabled: true
      - trash_id: a7bb1539fd147256b21b1098f3dc2016  # [SQP] SQP-5
        name: SQP-5 (Encode)
        qualities:
          - name: WEB|Bluray|2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
              - Bluray-2160p
        reset_unmatched_scores:
          enabled: true

    # Custom Format Groups
    # https://github.com/TRaSH-Guides/Guides/tree/master/docs/json/radarr/cf-groups
    custom_format_groups:
      add:
        - trash_id: 7fc2751eef7e6bdc70b74136e5e35c76  # [HDR Formats] DV (w/o HDR fallback)
        - trash_id: 1616617ab3a14397a2b2321bcbda44d1  # [HDR Formats] DV Boost
        - trash_id: b29413a7487478fe98228ce79e5689e4  # [HDR Formats] HDR10+ Boost
        - trash_id: c4492eebd0c2ddc14c2c91623aa7f95d  # [Optional] Miscellaneous SQP
          select:
            - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
            - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
            - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
            - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
            - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
            - f537cf427b64c38c8e36298f657e4828 # Scene
        - trash_id: f4f1474b963b24cf983455743aa9906c  # [Optional] Movie Versions
          select:
            # - eecf3a857724171f968a66cb5719e152 # IMAX -- can't remember why I removed this
            - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        - trash_id: 47f0d69750de9e16855915fa73bb7b08  # [Optional] SDR
          select:
            - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)

