# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# 1080p Radarr
radarr:
  radarrsd:
    base_url: !secret radarr_url
    api_key: !secret radarr_api
    media_naming:
      folder: default
      movie:
        rename: true
        standard: plex-tmdb
    media_management:
      propers_and_repacks: do_not_prefer
    delete_old_custom_formats: true

    # Quality Definition
    quality_definition:
      type: sqp-streaming
    
    # Quality Profiles
    # https://github.com/TRaSH-Guides/Guides/tree/master/docs/json/radarr/quality-profiles
    quality_profiles:
      - trash_id: 90a3370d2d30cbaf08d9c23b856a12c8  # [SQP] SQP-1 WEB (1080p)
        name: SQP-1 WEB (1080p) # Override name from JSON
        reset_unmatched_scores:
          enabled: true

    # Custom Format Groups
    # https://github.com/TRaSH-Guides/Guides/tree/master/docs/json/radarr/cf-groups
    custom_format_groups:
      add:
      - trash_id: 9337080378236ce4c0b183e35790d2a7  # [Optional] Miscellaneous
        select:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
      - trash_id: f4f1474b963b24cf983455743aa9906c  # [Optional] Movie Versions
        select:
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
