# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# 1080p Sonarr
sonarr:
  web-1080p-v4:
    base_url: !secret sonarr_url
    api_key: !secret sonarr_api
    media_naming:
      episodes:
        standard: default
    media_management:
      propers_and_repacks: do_not_prefer
    delete_old_custom_formats: true

    # Quality Definition
    quality_definition:
      type: series

    # Quality Profiles
    # https://github.com/TRaSH-Guides/Guides/tree/master/docs/json/sonarr/quality-profiles
    quality_profiles:
      - trash_id: 72dae194fc92bf828f32cde7744e51a1  # WEB-1080p
        reset_unmatched_scores:
          enabled: true
    
    # Custom Format Groups
    # https://github.com/TRaSH-Guides/Guides/tree/master/docs/json/sonarr/cf-groups
    custom_format_groups:
      add:
        - trash_id: f4a0410a1df109a66d6e47dcadcce014  # [Optional] Miscellaneous
          select:
            - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
            - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
            - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
            - 06d66ab109d4d2eddb2794d21526d140 # Retags
            - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        - trash_id: d920fd959d220306888f40b6f38e1578  # [Optional] Season Packs
